/**
 * Product video mapping — auto-generated by scripts/scrape-product-videos.ts
 * Products scanned: 705, with videos: 26
 * Generated: 2026-09-19T17:31:15.850Z
 */

export type ProductVideo = {
  fileId: string;
  label?: string;
};

const VIDEOS: Record<string, ProductVideo[]> = {
  "10": [
    { fileId: "1-Z31GtZeGW8JY_E9RjWv01Rj5COP08Dy", label: "2025-06-26-151959803" },
    { fileId: "1-ZcH7dQ34Y6tyd2gkY8Dvf91obzMpD2w", label: "2025-06-26-152027486" },
    { fileId: "1-gt8kClm8R9bw3MC6qvR5nZPp78AC4V3", label: "2025-06-27-091418345" },
  ],
  "1039": [
    { fileId: "1p5eiMlI8egkoCklKyfk28sTeXp6STRpL", label: "amigoss03 - 7571780978201480466" },
    { fileId: "16XfMtsGCEt3KmWq6Kd8Uqv6E02MiOU5d", label: "bersih bersinar" },
    { fileId: "1ajqBrdNU2IcEi-sRgUphAfhzzIcQGIpS", label: "bersihbersinar" },
  ],
  "1041": [
    { fileId: "1CWxYkllHKjl_IRdV7MCKB2U6LjsqeGKq", label: "download (1)" },
    { fileId: "1EWkDrLnJOqRxphRcBbA6iVXXQcOG1JIE", label: "id-11110105-6ko2f-mcu9pan1umfs86.16000101753941520" },
    { fileId: "1XVujcwiQpg3UZfb2uNy0Ax_xTn07FJ9p", label: "id-11110105-6vdv4-midte6sh6cxsd0.16000031766020991" },
  ],
  "1042": [
    { fileId: "1XBygpAJ0X9Wm0W1XCRm1PFDMLHJiYYpL", label: "Bikin toilet kamu makin wangi dan bersih! Bisa basmi kuman juga loh, kalo basmi mulut netizen siiii kayaknya…. Bisa juga. Ayo langsung checkout!" },
    { fileId: "1sBUqjb6Z4lf5-kXVSZsktXBtjCUCFPPH", label: "gammadzaki - 7573406627194359048" },
    { fileId: "1J-cVVlMVzckq7MRbYuP2nWPhWSoO-hoi", label: "Glow home pembersih toilet dan desinfektan" },
  ],
  "1255": [
    { fileId: "1xV_RKAJ5WTYZDjXEem0O09VRe6E__IAb", label: "snaptik_7366098695361842437_v2" },
    { fileId: "1JSY1omGbI-P79nB1m02TsnOK5lUyfnY9", label: "snaptik_7499407267729509687_v2" },
    { fileId: "1KA-ZGJmjA_wW-DDbiFCD5BES40DYJm7v", label: "snaptik_7519348439424060690_v2" },
  ],
  "1261": [
    { fileId: "1OevYXH-nPPp7K72GB9Z4niMGO6x7oyzX", label: "snaptik_7290540485888789765_v3" },
    { fileId: "1d8ghgeZ5eoGZGRXDAEgrA-x2SlNNiTE_", label: "snaptik_7310489490416569606_v3" },
    { fileId: "1s19omxkOs-_Z6c_KjYBfoPO7zFEKU9nf", label: "snaptik_7333964857370365190_v3" },
  ],
  "1280": [
    { fileId: "1fIx-MgzJ0dlG1KGyrkNl_C6Rkw_DxIlY", label: "id-11110105-6vfep-mlyjhuk5ckjkf9.16000081773813323" },
    { fileId: "1Ym8OG1eaJNxBvsQLZcevalbNaZ2sDE69", label: "lv_0_20260702101723" },
    { fileId: "1VEZpISBai1IpDLTdNUGM_XZRMw2vg7iX", label: "lv_0_20260702101936" },
  ],
  "1315": [
    { fileId: "10jj-ruLGjLVAFMwLP0T13ZqlZnVUUW3V", label: "snaptik_7419476072451804421_v3" },
  ],
  "1326": [
    { fileId: "1XBygpAJ0X9Wm0W1XCRm1PFDMLHJiYYpL", label: "Bikin toilet kamu makin wangi dan bersih! Bisa basmi kuman juga loh, kalo basmi mulut netizen siiii kayaknya…. Bisa juga. Ayo langsung checkout!" },
    { fileId: "1sBUqjb6Z4lf5-kXVSZsktXBtjCUCFPPH", label: "gammadzaki - 7573406627194359048" },
    { fileId: "1J-cVVlMVzckq7MRbYuP2nWPhWSoO-hoi", label: "Glow home pembersih toilet dan desinfektan" },
  ],
  "1357": [
    { fileId: "1XRtUKQzYrogytP2SfHsXcEIsOegdEd26", label: "Asset 1" },
    { fileId: "1XkCQHj2qJ-Mfsm7aPtdNQ3XwAcUTm4JN", label: "Asset 2" },
    { fileId: "1KuGiUJnUnWXFtRT6rQfeXVlIW7Lhbwp8", label: "7634160517979983125" },
  ],
  "1404": [
    { fileId: "1FjNxx94-Q3RoCGeDbKLMsqagdspzqWRf", label: "lv_0_20260216115108" },
    { fileId: "1huQF2SCkPvoDO8eVpe8PDRbPrBAvrbzw", label: "lv_0_20260425084146" },
    { fileId: "10lzJQTuYJ3wYw_dWsISljTcVMubGG1U_", label: "lv_0_20260425085249" },
  ],
  "1463": [
    { fileId: "1hCu1uU3kpFliUOHtX8A0j3TBR41hQe75", label: "0801(1)" },
    { fileId: "1Z1iSqU3eBkJFEeSqATGdO8lzTGjb7ooo", label: "Long clutch 2" },
    { fileId: "15qLencV0RSo_8uCtsFmXZySNLOKBOdrX", label: "Long clutch 3" },
  ],
  "1593": [
    { fileId: "14MliLLweJj88l8o3qN53-eLw4aIpzO2l", label: "Video 1" },
    { fileId: "1XtbjSTGzeFMmslk3hywLsjWHRcd_ySeK", label: "Video 2" },
  ],
  "1754": [
    { fileId: "1sN0OsvYTAuwZ_GhBztHNOFV57mCRuhed", label: "mentahanpengemuk1" },
    { fileId: "1EC-E-oDHiuCp9NhroNvixZDnoEiJ5Kf_", label: "mentahanpengemuk10" },
    { fileId: "1RYlE6Mpr5HwanTtnSPX8gV_G9L5QwagH", label: "mentahanpengemuk2" },
  ],
  "2145": [
    { fileId: "13qrPe2r1rmot6Gtz3_D9xuMTaKTK7n_Z", label: "M10formula" },
    { fileId: "1Z8Gs1EdM-DILWftyooq90XKqa1q4OS1E", label: "M11formula" },
    { fileId: "15K5NQ3iUlLUlCK3M9AJZ39aE3TULHQ82", label: "M12formula" },
  ],
  "2149": [
    { fileId: "1j3KlgD0-DH0gjzdQF8y5nrvcvud5CquW", label: "Formula 1" },
    { fileId: "1dZRlBcV39-Ppnlg-y-i-CZ-ihYGsBuUi", label: "Formula 2" },
    { fileId: "1u8elh5GSB6xREvWcW7Hw9LhDja8fXqQH", label: "Formula 3" },
  ],
  "2193": [
    { fileId: "1AyagSPonvwN1TDKmoYLYLAFOW4mJdyjY", label: "Adova Meili Nutricream 001" },
    { fileId: "1o_i6xB5hfAaKdUjFx2yirKxMUuG9aICz", label: "Adova Meili Nutricream 002" },
    { fileId: "19snjWhiFgR6ucoIHvgzhhSJeaCT2N7HO", label: "Adova Meili Nutricream 003" },
  ],
  "2194": [
    { fileId: "1AyagSPonvwN1TDKmoYLYLAFOW4mJdyjY", label: "Adova Meili Nutricream 001" },
    { fileId: "1o_i6xB5hfAaKdUjFx2yirKxMUuG9aICz", label: "Adova Meili Nutricream 002" },
    { fileId: "19snjWhiFgR6ucoIHvgzhhSJeaCT2N7HO", label: "Adova Meili Nutricream 003" },
  ],
  "2195": [
    { fileId: "1AyagSPonvwN1TDKmoYLYLAFOW4mJdyjY", label: "Adova Meili Nutricream 001" },
    { fileId: "1o_i6xB5hfAaKdUjFx2yirKxMUuG9aICz", label: "Adova Meili Nutricream 002" },
    { fileId: "19snjWhiFgR6ucoIHvgzhhSJeaCT2N7HO", label: "Adova Meili Nutricream 003" },
  ],
  "2196": [
    { fileId: "1AyagSPonvwN1TDKmoYLYLAFOW4mJdyjY", label: "Adova Meili Nutricream 001" },
    { fileId: "1o_i6xB5hfAaKdUjFx2yirKxMUuG9aICz", label: "Adova Meili Nutricream 002" },
    { fileId: "19snjWhiFgR6ucoIHvgzhhSJeaCT2N7HO", label: "Adova Meili Nutricream 003" },
  ],
  "2197": [
    { fileId: "1AyagSPonvwN1TDKmoYLYLAFOW4mJdyjY", label: "Adova Meili Nutricream 001" },
    { fileId: "1o_i6xB5hfAaKdUjFx2yirKxMUuG9aICz", label: "Adova Meili Nutricream 002" },
    { fileId: "19snjWhiFgR6ucoIHvgzhhSJeaCT2N7HO", label: "Adova Meili Nutricream 003" },
  ],
  "2198": [
    { fileId: "1ZcWv1b3a8Vfvxh_ck8kzDfNtLOu_VGtg", label: "3D Nose 1" },
    { fileId: "1wl5ztvoFWBgPRY3F8-8cX1Gd2DvJFjjQ", label: "3D Nose 2" },
    { fileId: "1YQ399DHm_jJnzADpnIWTWjVs9TUhwhfn", label: "3D Nose 3" },
  ],
  "2200": [
    { fileId: "16Yi0yyYEVYhLbvXSYwwNcBd0Q7ZwbBhr", label: "BODY COMPOUND 1" },
    { fileId: "1G6PJ72FXK-VUQsze5R4_5HiOFzqst87e", label: "BODY COMPOUND 2" },
  ],
  "2201": [
    { fileId: "1dTtHUiKql3GhW104FsRbEjcImhogouhN", label: "Hot-selling surveillance light bulb camera 360-degree panoramic camera surveillance wifi indoor HD night vision shaking head machine" },
    { fileId: "1YwtefUazwtlMKw41rO3HhIIv956OAgVP", label: "video-463785917170" },
  ],
  "2203": [
    { fileId: "18T_BFGnlAxbDJDH_pj3lqiOMKX08ww8j", label: "VIDEO DODO LABEL" },
  ],
  "2210": [
    { fileId: "1MRVPjepwggor5vxo47LYa05KyKt6Rt9o", label: "Lem Pengganti Paku 1" },
    { fileId: "188O1bbASwClhCguGGH7qdA4DjqBHcMea", label: "Lem Pengganti Paku 2" },
    { fileId: "18iRnfZzVj4bnxuxecE1xMiTbweG_onc4", label: "Lem Pengganti Paku 3" },
  ],
  "2224": [
    { fileId: "1EAopD8Zra9LHwslf8qVzGbR0m6aH6cej", label: "Stiker Kaca Mobil Anti Air 1" },
    { fileId: "1d7dUYJSvLR0dpB6dLj9Q1_IynPql_FqH", label: "Stiker Kaca Mobil Anti Air 2" },
    { fileId: "1wVQyvxOlMD19PPZmeHFCIFFsNEbGJ6yC", label: "Stiker Kaca Mobil Anti Air 3" },
  ],
  "2228": [
    { fileId: "1Tl49mvBlZRsQMcDm02Xw9d4-b_Qleevl", label: "ads no" },
    { fileId: "1weCH6pFLg5cowRPWbwIEe3Pt2SCt9K39", label: "ads pembesar mr.P" },
  ],
};

export function getProductVideos(productId: string): ProductVideo[] {
  return VIDEOS[productId] ?? [];
}

export function driveEmbedUrl(fileId: string): string {
  return `https://drive.google.com/file/d/${fileId}/preview`;
}

export function driveStreamUrl(fileId: string): string {
  return `https://drive.usercontent.google.com/download?id=${fileId}&export=download`;
}