/**
 * Product video mapping — auto-generated by scripts/scrape-product-videos.ts
 * Products scanned: 705, with videos: 126
 * Generated: 2026-09-20T17:18:00.000Z
 */

export type ProductVideo = {
  fileId: string;
  label?: string;
};

const VIDEOS: Record<string, ProductVideo[]> = {
  "10": [
    { fileId: "1-Z31GtZeGW8JY_E9RjWv01Rj5COP08Dy", label: "2025-06-26-151959803" },
    { fileId: "1-ZcH7dQ34Y6tyd2gkY8Dvf91obzMpD2w", label: "2025-06-26-152027486" },
    { fileId: "1-gt8kClm8R9bw3MC6qvR5nZPp78AC4V3", label: "2025-06-27-091418345" },
  ],
  "11": [
    { fileId: "1Z3_Md20m13iWJ0_tSUpTOcmnkfhylws6", label: "Video 1" },
    { fileId: "1J4wydVwfYp4MHGz4iroEs6QjzdtWGbEX", label: "Video 2" },
    { fileId: "1dCHL6YpE7VHvJQBLRe7Serkr-U0t9_xW", label: "Video 3" },
  ],
  "18": [
    { fileId: "1CpbQnAVpkOz55YZOLLDoOgT7LEXECBlC", label: "Video 1" },
    { fileId: "1uGakV7vow4RbNz59FPrLhhwIN3iCE51R", label: "Video 2" },
  ],
  "721": [
    { fileId: "18wK401nsvySzxtfr4HpDxRvkNoH5AxzZ", label: "Video 1" },
    { fileId: "1z0MuyPV00FcB6thwoYmcMxEMteCYDfEV", label: "Video 2" },
    { fileId: "1VNOX56mVGNITd7Zzn6yhyh-QRxohNKHW", label: "Video 3" },
  ],
  "1039": [
    { fileId: "1p5eiMlI8egkoCklKyfk28sTeXp6STRpL", label: "amigoss03 - 7571780978201480466" },
    { fileId: "16XfMtsGCEt3KmWq6Kd8Uqv6E02MiOU5d", label: "bersih bersinar" },
    { fileId: "1ajqBrdNU2IcEi-sRgUphAfhzzIcQGIpS", label: "bersihbersinar" },
  ],
  "1041": [
    { fileId: "1CWxYkllHKjl_IRdV7MCKB2U6LjsqeGKq", label: "download (1)" },
    { fileId: "1EWkDrLnJOqRxphRcBbA6iVXXQcOG1JIE", label: "id-11110105-6ko2f-mcu9pan1umfs86.16000101753941520" },
    { fileId: "1XVujcwiQpg3UZfb2uNy0Ax_xTn07FJ9p", label: "id-11110105-6vdv4-midte6sh6cxsd0.16000031766020991" },
  ],
  "1042": [
    { fileId: "1XBygpAJ0X9Wm0W1XCRm1PFDMLHJiYYpL", label: "Bikin toilet kamu makin wangi dan bersih! Bisa basmi kuman juga loh, kalo basmi mulut netizen siiii kayaknya…. Bisa juga. Ayo langsung checkout!" },
    { fileId: "1sBUqjb6Z4lf5-kXVSZsktXBtjCUCFPPH", label: "gammadzaki - 7573406627194359048" },
    { fileId: "1J-cVVlMVzckq7MRbYuP2nWPhWSoO-hoi", label: "Glow home pembersih toilet dan desinfektan" },
  ],
  "1049": [
    { fileId: "1nUpbp5xtdA9Rds1eNI23hOm1bF76LWwl", label: "Video 1" },
    { fileId: "1om1oRX8E4fK6mtLCPQOm_nUwMMbhzOP3", label: "Video 2" },
    { fileId: "1xkJJZR1J9EXHFwm_KPTAPyFhLcNGena-", label: "Video 3" },
  ],
  "1255": [
    { fileId: "1xV_RKAJ5WTYZDjXEem0O09VRe6E__IAb", label: "snaptik_7366098695361842437_v2" },
    { fileId: "1JSY1omGbI-P79nB1m02TsnOK5lUyfnY9", label: "snaptik_7499407267729509687_v2" },
    { fileId: "1KA-ZGJmjA_wW-DDbiFCD5BES40DYJm7v", label: "snaptik_7519348439424060690_v2" },
  ],
  "1259": [
    { fileId: "1GnS9YLgCp5NTJoSgFFhF06JPnYqrneyH", label: "Video 1" },
    { fileId: "1dEQ5yavjhme1_WQUxdcwoJWMKO3qJmrU", label: "Video 2" },
    { fileId: "1psMp0Xk9Yj2SevzaKMViI20LL5AtWSS5", label: "Video 3" },
  ],
  "1261": [
    { fileId: "1OevYXH-nPPp7K72GB9Z4niMGO6x7oyzX", label: "snaptik_7290540485888789765_v3" },
    { fileId: "1d8ghgeZ5eoGZGRXDAEgrA-x2SlNNiTE_", label: "snaptik_7310489490416569606_v3" },
    { fileId: "1s19omxkOs-_Z6c_KjYBfoPO7zFEKU9nf", label: "snaptik_7333964857370365190_v3" },
  ],
  "1263": [
    { fileId: "1xV0UCG2wDtDb5FAtFI1MWlI4lwILZIlv", label: "Video 1" },
    { fileId: "1TTcW1-gUVikec0FSPQ1XkPAQmWiG5Vrt", label: "Video 2" },
  ],
  "1264": [
    { fileId: "1_oMZRqRMe_bkkhtnYGR3gWlKvOBv2kte", label: "Video 1" },
  ],
  "1265": [
    { fileId: "12J5znH5yCRLtImv_fAxugx8u72KpY1bw", label: "Video 1" },
  ],
  "1266": [
    { fileId: "1lE__AwUrVRK18ZIO8UYQ9zN2J4Uc_G8p", label: "Video 1" },
  ],
  "1267": [
    { fileId: "1k0q1Q0hA5FdXzZBFybXmlrnfo4EdWa-t", label: "Video 1" },
  ],
  "1268": [
    { fileId: "1JBAK1B1Z5nn_aCigjBUXefaCRooxf-2H", label: "Video 1" },
    { fileId: "10ErcG6PSq6PltMwDW0BX_Zx5MlKnRrF9", label: "Video 2" },
    { fileId: "144IInjbH3B3DgZK29K1_zji4P7t0AfHC", label: "Video 3" },
  ],
  "1269": [
    { fileId: "19kgrHa_O_4PrI0VsLWMaDbRH_uoIsvD-", label: "Video 1" },
    { fileId: "1rifW4AZ_L-XrmPlJ4tv8IaYYNujXGZ1A", label: "Video 2" },
    { fileId: "1N61zCX1sSYGuOdTVlTfudtshlPOqCokn", label: "Video 3" },
  ],
  "1272": [
    { fileId: "1dp6l6wlU9D6VG3fhvygXWxo4XUhgF4gU", label: "Video 1" },
  ],
  "1274": [
    { fileId: "1NQp0RRAl6gZ1W6x1UJEwnQ0S8zI5iRX3", label: "Video 1" },
  ],
  "1275": [
    { fileId: "13YhWvEGC8oJoBPoRcuS8YfBz5iYh8OTL", label: "Video 1" },
    { fileId: "1-5mS-aMk4fA2SXBn2M1tgHefcd-4keSA", label: "Video 2" },
    { fileId: "1QO5YuAdC-HOMAGtBwHCsjmuhVISS5mKg", label: "Video 3" },
  ],
  "1280": [
    { fileId: "1fIx-MgzJ0dlG1KGyrkNl_C6Rkw_DxIlY", label: "id-11110105-6vfep-mlyjhuk5ckjkf9.16000081773813323" },
    { fileId: "1Ym8OG1eaJNxBvsQLZcevalbNaZ2sDE69", label: "lv_0_20260702101723" },
    { fileId: "1VEZpISBai1IpDLTdNUGM_XZRMw2vg7iX", label: "lv_0_20260702101936" },
  ],
  "1281": [
    { fileId: "1tzoR5sl_8-RewzgAxI-oVXiw136LueHh", label: "Video 1" },
  ],
  "1283": [
    { fileId: "1zo2viYf7zOSeOXxN6zzYoodoAY_Ninq7", label: "Video 1" },
    { fileId: "1iB-pfoT-F31C0QWTKYCYm8KmyQcrHlu6", label: "Video 2" },
    { fileId: "15H3ejqFGjs4PmmB_q8TXE5ldfbQZzUpF", label: "Video 3" },
  ],
  "1289": [
    { fileId: "1t1oJRiJKFcMlHfyaBszNgASUfcuHWAYI", label: "Video 1" },
    { fileId: "1ASyBG-EX9fvprCj70mkkhkiPgSG98P5T", label: "Video 2" },
    { fileId: "1RYdaa7FEHk4p_J1xQDK4yAxm-BrwNb0Q", label: "Video 3" },
  ],
  "1315": [
    { fileId: "10jj-ruLGjLVAFMwLP0T13ZqlZnVUUW3V", label: "snaptik_7419476072451804421_v3" },
  ],
  "1316": [
    { fileId: "1cE_yqP8DQkFhCXYyu_N7yNv2MviV36jy", label: "Video 1" },
  ],
  "1317": [
    { fileId: "1uva1GHOZSkVVKLfvXiYPKC3warFi_Pdk", label: "Video 1" },
    { fileId: "1ajqBrdNU2IcEi-sRgUphAfhzzIcQGIpS", label: "Video 2" },
    { fileId: "16XfMtsGCEt3KmWq6Kd8Uqv6E02MiOU5d", label: "Video 3" },
  ],
  "1318": [
    { fileId: "1ZF4_CoksHXnO3kbnrfBvQauJwLRGgehR", label: "Video 1" },
    { fileId: "1RdhInGSE-TlBK39I2IiTbm9jpC7PsUpz", label: "Video 2" },
    { fileId: "1xkJJZR1J9EXHFwm_KPTAPyFhLcNGena-", label: "Video 3" },
  ],
  "1319": [
    { fileId: "1bJrZjBFl8u3Hd0StxxA4Zj0Mwm2bocR3", label: "Video 1" },
    { fileId: "1Zj0RB6DiBtZNEeCkGJZl_Q4d8pgdgnxd", label: "Video 2" },
    { fileId: "1ikeICGu3hGXGbrOWLfIwAhpmuF1lPt2N", label: "Video 3" },
  ],
  "1324": [
    { fileId: "1H6P-IR6gDpWRBN1bkCnejsMEhYUM5Z5V", label: "Video 1" },
    { fileId: "1CWxYkllHKjl_IRdV7MCKB2U6LjsqeGKq", label: "Video 2" },
    { fileId: "1EWkDrLnJOqRxphRcBbA6iVXXQcOG1JIE", label: "Video 3" },
  ],
  "1326": [
    { fileId: "1XBygpAJ0X9Wm0W1XCRm1PFDMLHJiYYpL", label: "Bikin toilet kamu makin wangi dan bersih! Bisa basmi kuman juga loh, kalo basmi mulut netizen siiii kayaknya…. Bisa juga. Ayo langsung checkout!" },
    { fileId: "1sBUqjb6Z4lf5-kXVSZsktXBtjCUCFPPH", label: "gammadzaki - 7573406627194359048" },
    { fileId: "1J-cVVlMVzckq7MRbYuP2nWPhWSoO-hoi", label: "Glow home pembersih toilet dan desinfektan" },
  ],
  "1328": [
    { fileId: "1V8Eu4U0Vh3vreJcdUDGwVYrMJfkEXG1S", label: "Video 1" },
    { fileId: "1YU8jRaLxZaPbnMVZFrpLZaHYAQxqUXPa", label: "Video 2" },
    { fileId: "1fIx-MgzJ0dlG1KGyrkNl_C6Rkw_DxIlY", label: "Video 3" },
  ],
  "1329": [
    { fileId: "1uKkLBrX6b05ZPGxYeiTDxRTVrRMcpewy", label: "Video 1" },
    { fileId: "1IE9Eu1i69vulBfNLS11FZW1-ItQbXtkM", label: "Video 2" },
    { fileId: "1WqFUceMcf1NNaI4l-WrxQHZ1O69ssiqV", label: "Video 3" },
  ],
  "1330": [
    { fileId: "1I02grFckzFeN_J1GLdtFhIlqZFW6dYTs", label: "Video 1" },
    { fileId: "1bIZH0chkpVii935sDITW8cnm0_V0uP_3", label: "Video 2" },
    { fileId: "15V7Efjwzp3XZKBgOhI1xotvc8-XQGvzX", label: "Video 3" },
  ],
  "1331": [
    { fileId: "1BUZFNoYJ62c9CwWsSM1Eu-PWWZk5mRAS", label: "Video 1" },
  ],
  "1332": [
    { fileId: "13LgQhKWjYLzK5upVOm4PrMbCKvswsVUU", label: "Video 1" },
    { fileId: "1Q2TQGxi4rRPuiKQyLjF8djGXMdZ_Xw0z", label: "Video 2" },
    { fileId: "1naP9C1sXSAzxM_2MTVknkkMQG_qUqe4s", label: "Video 3" },
  ],
  "1333": [
    { fileId: "1kmoLVl9LFwl8pTmCFmGW3iZVZqo-XQJJ", label: "Video 1" },
    { fileId: "19Ib4406WOS62400Z-asbDUrPVeV4K4FI", label: "Video 2" },
  ],
  "1334": [
    { fileId: "1Ly5n2y7gy-Jrfu9qxi7EQ6qSkEGZUkP2", label: "Video 1" },
  ],
  "1335": [
    { fileId: "1eTAFALT8Ohynk2d44lEIeFGyGEkZ-bem", label: "Video 1" },
    { fileId: "1RoK1iNV6QLDp1ePDTakij_pw1xR0-mnl", label: "Video 2" },
    { fileId: "1Eqjsk3wWHyE8FUwlKDpcsJHvZx4gwwj5", label: "Video 3" },
  ],
  "1347": [
    { fileId: "1PoeX7YKqDCtLwGByCzepcSXpWQEeYtFm", label: "Video 1" },
    { fileId: "1roK7vdnW8Frw9Ru0uBdUAIArOaUO6Pvq", label: "Video 2" },
    { fileId: "1eNw9YS_sV5VoQiboCjjiO39p3leQ4LQK", label: "Video 3" },
  ],
  "1357": [
    { fileId: "1XRtUKQzYrogytP2SfHsXcEIsOegdEd26", label: "Asset 1" },
    { fileId: "1XkCQHj2qJ-Mfsm7aPtdNQ3XwAcUTm4JN", label: "Asset 2" },
    { fileId: "1KuGiUJnUnWXFtRT6rQfeXVlIW7Lhbwp8", label: "7634160517979983125" },
  ],
  "1378": [
    { fileId: "1eqJpeAsivua63vKL5SXepTmD0SF-NYY8", label: "Video 1" },
    { fileId: "1llCAbh-5wl0nM8RN0u1ZvT6SfMwwgPNF", label: "Video 2" },
  ],
  "1389": [
    { fileId: "1ZXbObgOMI5cHruZHIRIVNbosNTjC3Q6D", label: "Video 1" },
    { fileId: "1hnXwMm062LglZKMT0upxkm8KQw4o_K6K", label: "Video 2" },
    { fileId: "1FfwXjzYPJW7Lczn8wqtQrJJn3ot5mR_Z", label: "Video 3" },
  ],
  "1390": [
    { fileId: "1hnXwMm062LglZKMT0upxkm8KQw4o_K6K", label: "Video 1" },
    { fileId: "13X3IyM1vLMIdZyzUO048zoouqonPf6nP", label: "Video 2" },
    { fileId: "1FfwXjzYPJW7Lczn8wqtQrJJn3ot5mR_Z", label: "Video 3" },
  ],
  "1393": [
    { fileId: "1k-NB_pnzQmzsFPWY6MJkcGRzYnIeebY9", label: "Video 1" },
  ],
  "1394": [
    { fileId: "1g_Wtlohs8jgrGfqO3YB0UJ5VCV_Apb3f", label: "Video 1" },
  ],
  "1395": [
    { fileId: "1b-Eq9NvujyiQMcHj_SsP7XKwsjKnH9HN", label: "Video 1" },
  ],
  "1397": [
    { fileId: "1BewBsmGnkBG5fJgHDyzjQjhHhL58PcWX", label: "Video 1" },
  ],
  "1398": [
    { fileId: "1b-Eq9NvujyiQMcHj_SsP7XKwsjKnH9HN", label: "Video 1" },
  ],
  "1404": [
    { fileId: "1FjNxx94-Q3RoCGeDbKLMsqagdspzqWRf", label: "lv_0_20260216115108" },
    { fileId: "1huQF2SCkPvoDO8eVpe8PDRbPrBAvrbzw", label: "lv_0_20260425084146" },
    { fileId: "10lzJQTuYJ3wYw_dWsISljTcVMubGG1U_", label: "lv_0_20260425085249" },
  ],
  "1445": [
    { fileId: "1n0iF6KCMd6DsrczFIL1D_BSBF_I52xWX", label: "Video 1" },
  ],
  "1446": [
    { fileId: "1plb0MSXcRs02eTlzcXTxu_6b1nRmWmKg", label: "Video 1" },
  ],
  "1451": [
    { fileId: "1kRSM7S0Xkes_MEDEKbF4kaggsXfgDh_9", label: "Video 1" },
    { fileId: "1D9pxEXA126wGT9mVVyoiJPyKZ851XoLB", label: "Video 2" },
  ],
  "1452": [
    { fileId: "1tIo5OaAgqiSXQ83uAgGfGvsg3dWHWpqM", label: "Video 1" },
    { fileId: "1syAH3Npykc34SW3okeQVZnGvskme0rLo", label: "Video 2" },
    { fileId: "12nX6JmQrY7R1gHuauUYkRVDG54W7i-Uc", label: "Video 3" },
  ],
  "1454": [
    { fileId: "1KP1Nqeqjtfdf_S4WGOFoX8qt8YReKjmY", label: "Video 1" },
  ],
  "1456": [
    { fileId: "1ZXbObgOMI5cHruZHIRIVNbosNTjC3Q6D", label: "Video 1" },
    { fileId: "1hnXwMm062LglZKMT0upxkm8KQw4o_K6K", label: "Video 2" },
    { fileId: "1FfwXjzYPJW7Lczn8wqtQrJJn3ot5mR_Z", label: "Video 3" },
  ],
  "1463": [
    { fileId: "1hCu1uU3kpFliUOHtX8A0j3TBR41hQe75", label: "0801(1)" },
    { fileId: "1Z1iSqU3eBkJFEeSqATGdO8lzTGjb7ooo", label: "Long clutch 2" },
    { fileId: "15qLencV0RSo_8uCtsFmXZySNLOKBOdrX", label: "Long clutch 3" },
  ],
  "1506": [
    { fileId: "1SsL8dPPcd8O775fmkEJHB_UpBWQ8EWj8", label: "Video 1" },
    { fileId: "1j3bsg1CoIKwtx7gwFzQwfR5YIT-JKuKa", label: "Video 2" },
    { fileId: "1053Ah1OrBt0Nj1UrdN5e_GTKeyZP67iC", label: "Video 3" },
  ],
  "1536": [
    { fileId: "1ibfnI5KBRyz9SEYxy1dnweNCxLo5LO2f", label: "Video 1" },
  ],
  "1539": [
    { fileId: "1gWEiASelj3gZe-8osG5HLGsZM_nO0gKU", label: "Video 1" },
  ],
  "1542": [
    { fileId: "1VwUC5G8xTodriWBy8BQaaSLti0GSqUZd", label: "Video 1" },
  ],
  "1543": [
    { fileId: "1ixzU1DlIH-W8hMCTkVD8qL7yzFp9cecV", label: "Video 1" },
  ],
  "1548": [
    { fileId: "16tp_zeFTBhFXseig7kgIfvHGWM4Y27Zk", label: "Video 1" },
  ],
  "1549": [
    { fileId: "1AtOCIaslBj_PK6ZNOAPabyUG1XvrNZD9", label: "Video 1" },
    { fileId: "1tmtOC3mfLQk9DC-dsJcLGPjHw7YfnuOd", label: "Video 2" },
    { fileId: "19FHreQAdyDXXG6IOjNuU6sfuupXpS5lO", label: "Video 3" },
  ],
  "1553": [
    { fileId: "13vAUVsy7_pnLlWGdiVLNYOBs8kxze_nk", label: "Video 1" },
    { fileId: "1PSbHVx8f54ePuuxlvz_12rZWM_7iAzJi", label: "Video 2" },
  ],
  "1558": [
    { fileId: "13UFa6Km79E-kufilt-MeI_2iI6Cb2SZi", label: "Video 1" },
    { fileId: "1mGgcENjJe3_cJ2xHD2VfwSuGT2fIfa-8", label: "Video 2" },
    { fileId: "1-eaotx2WOldm77OvZYw2a2UREjImFTi0", label: "Video 3" },
  ],
  "1559": [
    { fileId: "1GDe05W4eLNm9yB-uDSZCAwV3ky2C7eMN", label: "Video 1" },
    { fileId: "1p0LBGFogCMoAmOWfDYbP_bToZWuNl-sp", label: "Video 2" },
    { fileId: "1CSVE8KGe8Vp26LTZW2Xg3dhov2Sl71Xs", label: "Video 3" },
  ],
  "1564": [
    { fileId: "1H8hIJyf2Ux4su1i4LYEYdnCGKky-GsNi", label: "Video 1" },
    { fileId: "1nKqPcZfymoOrjcigdHml23R0izOu6tIX", label: "Video 2" },
    { fileId: "1n4PpKcXMWDkxEN2rCDoFV6PgpKd2trl9", label: "Video 3" },
  ],
  "1565": [
    { fileId: "1sREBiJMu0qGH2IOmRGO6gVoUTl6nkt-S", label: "Video 1" },
    { fileId: "1nc1NevG32XbMYbhCVvF0wGNuWfA4TMBM", label: "Video 2" },
    { fileId: "1YGJfOC1BMCC0fBxHpk9W570aFXjmEPfp", label: "Video 3" },
  ],
  "1572": [
    { fileId: "1UojSBVFUV7Q_ylcLuyhwGqwVNQd-EUjR", label: "Video 1" },
  ],
  "1573": [
    { fileId: "1v7sGSHyn3tuGxsZeu6NaUqu0fQ1GmsrE", label: "Video 1" },
    { fileId: "1WAXdIfF6K7lpyz22QxSkwr6ThtPawS6B", label: "Video 2" },
    { fileId: "1cbAXI78fGrsrIu9p9xQbJXVDzkwaCGYb", label: "Video 3" },
  ],
  "1593": [
    { fileId: "14MliLLweJj88l8o3qN53-eLw4aIpzO2l", label: "Video 1" },
    { fileId: "1XtbjSTGzeFMmslk3hywLsjWHRcd_ySeK", label: "Video 2" },
  ],
  "1637": [
    { fileId: "1ubqaIhz_vn5X5KFi0Y1zKsnTDzOg1ht4", label: "Video 1" },
    { fileId: "1iaOvMTZnvcfAeZICqu0pRrcMQCd0zJ8q", label: "Video 2" },
    { fileId: "1oaRccpcGlHBRY07bFKeFvDER7DHqCJBH", label: "Video 3" },
  ],
  "1639": [
    { fileId: "1eyuJXdPD5OCx6LyiSBByC8Yz5W6wjZR2", label: "Video 1" },
    { fileId: "1vr-Ov3i_mYkTLuXvAGrFei4BSldbCkN6", label: "Video 2" },
    { fileId: "1JrWYvKMb7n1b7r4DNYjej1sOCuTFmZ4u", label: "Video 3" },
  ],
  "1641": [
    { fileId: "1mvPLvkuTuSwfvpywWawf5cjkocyvMofZ", label: "Video 1" },
    { fileId: "1dkzWkWDUuVYBFk64PyI0A4c93O7FwCQi", label: "Video 2" },
    { fileId: "1D_XgxSqJ-6ybIL7-_W3YvPkNeugJZz7M", label: "Video 3" },
  ],
  "1642": [
    { fileId: "1DD55s844Hqu4Rmcn2X8P4Lt0L6aGxVzp", label: "Video 1" },
    { fileId: "1eKqkdhdlMl8TUpPT2X_XlW2QJEVRUs5d", label: "Video 2" },
    { fileId: "1C1ME2Ko_qw9TFD_jca1BW1Om6siYqGlC", label: "Video 3" },
  ],
  "1643": [
    { fileId: "1YMTnaqLMtpc66uSLwq5D2_DNvkD_R0dK", label: "Video 1" },
    { fileId: "1n9WkSfFDlbIYUuFAuParHOCzVQQ5KNAT", label: "Video 2" },
    { fileId: "1aHKNtJDKVbRwS0Z5mB71DmvhQK8JL8Rj", label: "Video 3" },
  ],
  "1644": [
    { fileId: "16YWMyxhBs_6yYDL__hw2GZVoe07teLQV", label: "Video 1" },
    { fileId: "1qcqSKtUA8J0BmW4hf7FkYWQyj9cPNnks", label: "Video 2" },
    { fileId: "1XjYpiaAIuAu6JGjlbCKluIH3zcxShznl", label: "Video 3" },
  ],
  "1645": [
    { fileId: "1u8RkLriaRtKoil6FT9kwfSH3wsRnI7Pc", label: "Video 1" },
    { fileId: "1SdxlVwwJu7pw1GV2MPoAVBpOgsIrCisD", label: "Video 2" },
    { fileId: "16Lf9Q_pM5OMITb6maeuyj_O21UVv-d6o", label: "Video 3" },
  ],
  "1646": [
    { fileId: "1EIwBMcAEVWTNssb1Uq4NJqbgxXCjEUbB", label: "Video 1" },
    { fileId: "1W7U5Tgy1c5HhX42_D3DvD5QHFpTDAKIe", label: "Video 2" },
    { fileId: "1gFFsO8kP0syPHQMNF48y6o-mR_1R1Wma", label: "Video 3" },
  ],
  "1653": [
    { fileId: "1tmtOC3mfLQk9DC-dsJcLGPjHw7YfnuOd", label: "Video 1" },
    { fileId: "1_LxMBRsy3a3Jmyr8qNiJghdkmAnGdnkL", label: "Video 2" },
    { fileId: "1IfoQprNnzcZspvLcKm83QKthA4ZwgOSC", label: "Video 3" },
  ],
  "1667": [
    { fileId: "1aYrOeVsyGcQawa1iE8I1VIqKkhbDdQL1", label: "Video 1" },
    { fileId: "1-cZigtdssiCOwOoqw0pQaXbro-qZeca9", label: "Video 2" },
    { fileId: "1Es6OItQy4hLVR2t4-_aUeU3Upo4cRQDr", label: "Video 3" },
  ],
  "1684": [
    { fileId: "11GmVMAa-027xiKQAraEbJsJHZR73HLeH", label: "Video 1" },
    { fileId: "13DwlWbH4h46KzSoVYvaju5BoPMtdyRNH", label: "Video 2" },
    { fileId: "18tfWrCpIif3ySUXObB_D6OHRLyWPl43W", label: "Video 3" },
  ],
  "1702": [
    { fileId: "1c-FyODldN22uYMn8oOZ3M-1HwEpxNslJ", label: "Video 1" },
    { fileId: "1n7U5RVMMf4RLlSBvp6PTsFxMOWztSRDB", label: "Video 2" },
  ],
  "1707": [
    { fileId: "1qRPLiYiJjGK5k4PRIsTHw7QZQBeZKpZH", label: "Video 1" },
    { fileId: "19PJTzYVpSaVyQwWdleG8IGQPDUmHv9vL", label: "Video 2" },
  ],
  "1732": [
    { fileId: "1Pr6M4qCndJDFHhu2cKklW8m79rxUgXXo", label: "Video 1" },
    { fileId: "1Em9hlX9Gtyf-HbZ5JxGO3l9VOl0eY-PI", label: "Video 2" },
  ],
  "1733": [
    { fileId: "10yCEa5-IWLKZDUnYHRiq6sa8u4aQbULN", label: "Video 1" },
  ],
  "1750": [
    { fileId: "1fCHKDK4LBTHRX7f-ExtCDo5LZWUgkg66", label: "Video 1" },
    { fileId: "1Ve1zAqL92fDrysfjLTJml7b3ztc7QR6C", label: "Video 2" },
    { fileId: "1kVzu9bZw4jOYMu1ZKC9MmTsS_oQQDESd", label: "Video 3" },
  ],
  "1648": [
    { fileId: "1YaAS4CkRN9YLdaySiVlZlEpOmhNvhfkR", label: "Video 1" },
    { fileId: "1xZj2-T9tHwg17CbvBkmdUyX-3j4sqnXK", label: "Video 2" },
    { fileId: "1gkaxqhh3alfBerNho9r9CdJg5goOj1Tw", label: "Video 3" },
  ],
  "1754": [
    { fileId: "1sN0OsvYTAuwZ_GhBztHNOFV57mCRuhed", label: "mentahanpengemuk1" },
    { fileId: "1EC-E-oDHiuCp9NhroNvixZDnoEiJ5Kf_", label: "mentahanpengemuk10" },
    { fileId: "1RYlE6Mpr5HwanTtnSPX8gV_G9L5QwagH", label: "mentahanpengemuk2" },
  ],
  "1755": [
    { fileId: "1gc4r4p2VSuTZP12G7m_uzxFCZwk48GcE", label: "Video 1" },
  ],
  "1777": [
    { fileId: "1wqjAJUmrxj11dWFYyLLEqm7Ota0udp6_", label: "Video 1" },
    { fileId: "1yV9XUulDP1vL_DUzDOo8iSZLlhqEO1Un", label: "Video 2" },
    { fileId: "1l4ffaPKslhJWVZ7e1gFlCtTTAhnn-nnb", label: "Video 3" },
  ],
  "1780": [
    { fileId: "1ezce1KKpVc5XZLsEdYkU2kFvRJG2MyNo", label: "Video 1" },
  ],
  "1781": [
    { fileId: "1Ee5YGSjT6mU3TNcfL-s5f0XBSb8L7w3_", label: "Video 1" },
    { fileId: "1yjVvYPa0kmotI1hYFesdjTY8I2WmHbt_", label: "Video 2" },
  ],
  "1804": [
    { fileId: "1Ns3-4kRy0UyLB_ss3FIG3Efn7Qdg9qE6", label: "Video 1" },
    { fileId: "1NeceoMCfFI558wt6daYWb1plgoETCU7T", label: "Video 2" },
  ],
  "1809": [
    { fileId: "1Ki9NvUJuTYKgp4lgPKB0kUsVF3XLx7ro", label: "Video 1" },
  ],
  "1816": [
    { fileId: "1qiXcFbVyY7yIHPwkIzTD1JiUtIhGqlv3", label: "Video 1" },
    { fileId: "1oXlg6Xs75zBycDymX5PUau7AEJgtTap4", label: "Video 2" },
    { fileId: "15-xh94l8eM91-4onBlYVEgFI0ed7a_gP", label: "Video 3" },
  ],
  "1840": [
    { fileId: "1z0qjoZXBFYJRmWNI4XBi9th_-6n9eqj6", label: "Video 1" },
    { fileId: "1EbpTDsbmSw7z39RO1IbPGe7llELS4a2h", label: "Video 2" },
    { fileId: "149ff2RrZ0EOC1F1JdRmvkABQs9VnnvPt", label: "Video 3" },
  ],
  "1885": [
    { fileId: "1Vkubfi0RXx0SWcHqHiVFyC-swB0ZY_YY", label: "Video 1" },
  ],
  "1997": [
    { fileId: "1oyabqknX2olXk6kQlh1upwHYcJUYN5WT", label: "Video 1" },
    { fileId: "12yvu9FyjttyR3KDgHoqRfvX54DvuaJpw", label: "Video 2" },
    { fileId: "1veegdqgl9K-NPtTB_hXvG64YmK1kWCQI", label: "Video 3" },
  ],
  "2120": [
    { fileId: "12IacAgd5WAOXj4SRVAGA7cYmRqKN-pzo", label: "Video 1" },
    { fileId: "1aEb_0JtGlql6YtwXiW3Ir5u2PTC5MkX4", label: "Video 2" },
    { fileId: "1zGB7IsJXVr1gchidUz4PGZBUS6mOomxQ", label: "Video 3" },
  ],
  "2121": [
    { fileId: "1Fvf7XGQyd9T4vgt2tCuLqglAk9vOSOxw", label: "Video 1" },
    { fileId: "1JK6uR_rKeaEvSTHSVaRWGuxWKOv9xow6", label: "Video 2" },
  ],
  "2122": [
    { fileId: "1Fvf7XGQyd9T4vgt2tCuLqglAk9vOSOxw", label: "Video 1" },
    { fileId: "1JK6uR_rKeaEvSTHSVaRWGuxWKOv9xow6", label: "Video 2" },
  ],
  "2134": [
    { fileId: "1FucZ-U-DhXcOtXiff6ixqEQQX3Jl8rpy", label: "Video 1" },
  ],
  "2135": [
    { fileId: "1DB4UGUZt4BOSbqI6jOygUlMs7jCx7aUB", label: "Video 1" },
    { fileId: "1SGdotoo4XGnkR6hR7qvbjayVXF39RNwk", label: "Video 2" },
    { fileId: "12ulb4XSjGBQqhU6P8voqGkPtTD5X4Tve", label: "Video 3" },
  ],
  "2136": [
    { fileId: "1_1ibAsTI6PZE_a-CZo1Ct5Nt5hbZrdBy", label: "Video 1" },
    { fileId: "1z_tIzns9eRO_XwOwql_J3ve7VGJUxYzT", label: "Video 2" },
    { fileId: "1-4Tx4-g4U2U0WZw8ixCVpZJQI2xYaPSt", label: "Video 3" },
  ],
  "2137": [
    { fileId: "1tPpa_obVOJdqv6RVh6ZzHr5xNeE52GVJ", label: "Video 1" },
    { fileId: "13QDZI9VFr3ovcYa8LisDjYvsvjwT0N_3", label: "Video 2" },
  ],
  "2138": [
    { fileId: "10Yp5KwGBwRllCtF_jXPfvBrl5HvhZNL6", label: "Video 1" },
    { fileId: "1C6aqufWB0evj8Ptwn9m4yD6qofG_SFWp", label: "Video 2" },
    { fileId: "1J-gcIb_pZ96Ail1jLWtkYrNqVCCMR0ec", label: "Video 3" },
  ],
  "2140": [
    { fileId: "1jLFVfjTqEel-1Bwg_h3RlgQIsiLYZMAu", label: "Video 1" },
  ],
  "2145": [
    { fileId: "13qrPe2r1rmot6Gtz3_D9xuMTaKTK7n_Z", label: "M10formula" },
    { fileId: "1Z8Gs1EdM-DILWftyooq90XKqa1q4OS1E", label: "M11formula" },
    { fileId: "15K5NQ3iUlLUlCK3M9AJZ39aE3TULHQ82", label: "M12formula" },
  ],
  "2149": [
    { fileId: "1j3KlgD0-DH0gjzdQF8y5nrvcvud5CquW", label: "Formula 1" },
    { fileId: "1dZRlBcV39-Ppnlg-y-i-CZ-ihYGsBuUi", label: "Formula 2" },
    { fileId: "1u8elh5GSB6xREvWcW7Hw9LhDja8fXqQH", label: "Formula 3" },
  ],
  "2148": [
    { fileId: "1L7lYSt5K2nf9-FxMLdCpUU4kqYF6sPkE", label: "Video 1" },
  ],
  "2151": [
    { fileId: "1s14bV8tEtJcAjrkAjgjuLh4UCgxosnMZ", label: "Video 1" },
  ],
  "2191": [
    { fileId: "1gZ0ztitIpK1GUOQ_mAipCWSx_29NdcKq", label: "Video 1" },
    { fileId: "1KrzmT3VxNmyp33x8hpTEo9DsghBmbR4Z", label: "Video 2" },
    { fileId: "1Z5hlMyc40xcbv0Zlmj9SDXRsVRscJ12v", label: "Video 3" },
  ],
  "2193": [
    { fileId: "1AyagSPonvwN1TDKmoYLYLAFOW4mJdyjY", label: "Adova Meili Nutricream 001" },
    { fileId: "1o_i6xB5hfAaKdUjFx2yirKxMUuG9aICz", label: "Adova Meili Nutricream 002" },
    { fileId: "19snjWhiFgR6ucoIHvgzhhSJeaCT2N7HO", label: "Adova Meili Nutricream 003" },
  ],
  "2194": [
    { fileId: "1AyagSPonvwN1TDKmoYLYLAFOW4mJdyjY", label: "Adova Meili Nutricream 001" },
    { fileId: "1o_i6xB5hfAaKdUjFx2yirKxMUuG9aICz", label: "Adova Meili Nutricream 002" },
    { fileId: "19snjWhiFgR6ucoIHvgzhhSJeaCT2N7HO", label: "Adova Meili Nutricream 003" },
  ],
  "2195": [
    { fileId: "1AyagSPonvwN1TDKmoYLYLAFOW4mJdyjY", label: "Adova Meili Nutricream 001" },
    { fileId: "1o_i6xB5hfAaKdUjFx2yirKxMUuG9aICz", label: "Adova Meili Nutricream 002" },
    { fileId: "19snjWhiFgR6ucoIHvgzhhSJeaCT2N7HO", label: "Adova Meili Nutricream 003" },
  ],
  "2196": [
    { fileId: "1AyagSPonvwN1TDKmoYLYLAFOW4mJdyjY", label: "Adova Meili Nutricream 001" },
    { fileId: "1o_i6xB5hfAaKdUjFx2yirKxMUuG9aICz", label: "Adova Meili Nutricream 002" },
    { fileId: "19snjWhiFgR6ucoIHvgzhhSJeaCT2N7HO", label: "Adova Meili Nutricream 003" },
  ],
  "2197": [
    { fileId: "1AyagSPonvwN1TDKmoYLYLAFOW4mJdyjY", label: "Adova Meili Nutricream 001" },
    { fileId: "1o_i6xB5hfAaKdUjFx2yirKxMUuG9aICz", label: "Adova Meili Nutricream 002" },
    { fileId: "19snjWhiFgR6ucoIHvgzhhSJeaCT2N7HO", label: "Adova Meili Nutricream 003" },
  ],
  "2198": [
    { fileId: "1ZcWv1b3a8Vfvxh_ck8kzDfNtLOu_VGtg", label: "3D Nose 1" },
    { fileId: "1wl5ztvoFWBgPRY3F8-8cX1Gd2DvJFjjQ", label: "3D Nose 2" },
    { fileId: "1YQ399DHm_jJnzADpnIWTWjVs9TUhwhfn", label: "3D Nose 3" },
  ],
  "2200": [
    { fileId: "16Yi0yyYEVYhLbvXSYwwNcBd0Q7ZwbBhr", label: "BODY COMPOUND 1" },
    { fileId: "1G6PJ72FXK-VUQsze5R4_5HiOFzqst87e", label: "BODY COMPOUND 2" },
  ],
  "2201": [
    { fileId: "1dTtHUiKql3GhW104FsRbEjcImhogouhN", label: "Hot-selling surveillance light bulb camera 360-degree panoramic camera surveillance wifi indoor HD night vision shaking head machine" },
    { fileId: "1YwtefUazwtlMKw41rO3HhIIv956OAgVP", label: "video-463785917170" },
  ],
  "2203": [
    { fileId: "18T_BFGnlAxbDJDH_pj3lqiOMKX08ww8j", label: "VIDEO DODO LABEL" },
  ],
  "2210": [
    { fileId: "1MRVPjepwggor5vxo47LYa05KyKt6Rt9o", label: "Lem Pengganti Paku 1" },
    { fileId: "188O1bbASwClhCguGGH7qdA4DjqBHcMea", label: "Lem Pengganti Paku 2" },
    { fileId: "18iRnfZzVj4bnxuxecE1xMiTbweG_onc4", label: "Lem Pengganti Paku 3" },
  ],
  "2224": [
    { fileId: "1EAopD8Zra9LHwslf8qVzGbR0m6aH6cej", label: "Stiker Kaca Mobil Anti Air 1" },
    { fileId: "1d7dUYJSvLR0dpB6dLj9Q1_IynPql_FqH", label: "Stiker Kaca Mobil Anti Air 2" },
    { fileId: "1wVQyvxOlMD19PPZmeHFCIFFsNEbGJ6yC", label: "Stiker Kaca Mobil Anti Air 3" },
  ],
  "2228": [
    { fileId: "1Tl49mvBlZRsQMcDm02Xw9d4-b_Qleevl", label: "ads no" },
    { fileId: "1weCH6pFLg5cowRPWbwIEe3Pt2SCt9K39", label: "ads pembesar mr.P" },
  ],
};

export function getProductVideos(productId: string): ProductVideo[] {
  return VIDEOS[productId] ?? [];
}

export function driveEmbedUrl(fileId: string): string {
  return `https://drive.google.com/file/d/${fileId}/preview`;
}

export function driveStreamUrl(fileId: string): string {
  return `https://drive.usercontent.google.com/download?id=${fileId}&export=download`;
}