/**
 * Product video mapping — auto-generated by scripts/scrape-product-videos.ts
 * Products scanned: 706, with videos: 24
 * Generated: 2026-09-19T09:38:55.139Z
 */

export type ProductVideo = {
  fileId: string;
  label?: string;
};

const VIDEOS: Record<string, ProductVideo[]> = {
  "10": [
    { fileId: "1-Z31GtZeGW8JY_E9RjWv01Rj5COP08Dy", label: "2025-06-26-151959803" },
    { fileId: "1-ZcH7dQ34Y6tyd2gkY8Dvf91obzMpD2w", label: "2025-06-26-152027486" },
    { fileId: "1-gt8kClm8R9bw3MC6qvR5nZPp78AC4V3", label: "2025-06-27-091418345" },
  ],
  "1039": [
    { fileId: "1p5eiMlI8egkoCklKyfk28sTeXp6STRpL", label: "amigoss03 - 7571780978201480466" },
    { fileId: "16XfMtsGCEt3KmWq6Kd8Uqv6E02MiOU5d", label: "bersih bersinar" },
    { fileId: "1ajqBrdNU2IcEi-sRgUphAfhzzIcQGIpS", label: "bersihbersinar" },
  ],
  "1041": [
    { fileId: "1CWxYkllHKjl_IRdV7MCKB2U6LjsqeGKq", label: "download (1)" },
    { fileId: "1EWkDrLnJOqRxphRcBbA6iVXXQcOG1JIE", label: "id-11110105-6ko2f-mcu9pan1umfs86.16000101753941520" },
    { fileId: "1XVujcwiQpg3UZfb2uNy0Ax_xTn07FJ9p", label: "id-11110105-6vdv4-midte6sh6cxsd0.16000031766020991" },
  ],
  "1042": [
    { fileId: "1XBygpAJ0X9Wm0W1XCRm1PFDMLHJiYYpL", label: "Bikin toilet kamu makin wangi dan bersih! Bisa basmi kuman juga loh, kalo basmi mulut netizen siiii kayaknya…. Bisa juga. Ayo langsung checkout!" },
    { fileId: "1sBUqjb6Z4lf5-kXVSZsktXBtjCUCFPPH", label: "gammadzaki - 7573406627194359048" },
    { fileId: "1J-cVVlMVzckq7MRbYuP2nWPhWSoO-hoi", label: "Glow home pembersih toilet dan desinfektan" },
  ],
  "1249": [
    { fileId: "1N6758Ao3AVNsNUpnLfSxDNAGp4Qp5G-G", label: "20260303_140515" },
    { fileId: "15m8i8X-jF1X1xxbue3b7l0dUDvLsu4_q", label: "20260303_140538" },
    { fileId: "1f5WwxV0PDwrv5EY87IWb5ea-tFC6EL5N", label: "20260303_140614" },
  ],
  "1258": [
    { fileId: "1YlpQXRel2TNsOTg6ASvvYlcvh5PNkQGr", label: "id-11110105-6ke19-m0jzi97xnh3bb9.16000081727168141" },
    { fileId: "1qmdTvYtwUvpswmIYvc8n47gxb17dP6x4", label: "id-11110105-6ke1i-ln9rteg91d3013.default" },
    { fileId: "1FCge7EZ1HsOe6wpfMbNN8rzSN0dqbVVu", label: "sg-11110106-6va2b-mkj1xee8uq6g32.16000101770696485" },
  ],
  "1259": [
    { fileId: "1psMp0Xk9Yj2SevzaKMViI20LL5AtWSS5", label: "id-11110105-6ke1d-lziknlmu702w39.16000081724903393" },
    { fileId: "1dEQ5yavjhme1_WQUxdcwoJWMKO3qJmrU", label: "snaptik_7152088371362352411_v3" },
    { fileId: "1GnS9YLgCp5NTJoSgFFhF06JPnYqrneyH", label: "snaptik_7475916394136128786_v3" },
  ],
  "1261": [
    { fileId: "1OevYXH-nPPp7K72GB9Z4niMGO6x7oyzX", label: "snaptik_7290540485888789765_v3" },
    { fileId: "1d8ghgeZ5eoGZGRXDAEgrA-x2SlNNiTE_", label: "snaptik_7310489490416569606_v3" },
    { fileId: "1s19omxkOs-_Z6c_KjYBfoPO7zFEKU9nf", label: "snaptik_7333964857370365190_v3" },
  ],
  "1263": [
    { fileId: "1TTcW1-gUVikec0FSPQ1XkPAQmWiG5Vrt", label: "id-11110105-6vg6n-ml1svj4ve3gm6f.16000081771831424" },
    { fileId: "1xV0UCG2wDtDb5FAtFI1MWlI4lwILZIlv", label: "snaptik_7631105704350518548_v3" },
  ],
  "1264": [
    { fileId: "1_oMZRqRMe_bkkhtnYGR3gWlKvOBv2kte", label: "id-11110105-6vdvl-mi12u4myqdc146.16000041765249910" },
  ],
  "1265": [
    { fileId: "12J5znH5yCRLtImv_fAxugx8u72KpY1bw", label: "id-11110105-6knal-m52fogkmek1462.16000081737001930" },
  ],
  "1266": [
    { fileId: "1lE__AwUrVRK18ZIO8UYQ9zN2J4Uc_G8p", label: "id-11110105-6kmiw-m52op92bthxy3d.16000081737017096" },
  ],
  "1267": [
    { fileId: "1k0q1Q0hA5FdXzZBFybXmlrnfo4EdWa-t", label: "SnapTik_App_7540499045714758968" },
  ],
  "1268": [
    { fileId: "144IInjbH3B3DgZK29K1_zji4P7t0AfHC", label: "id-11110105-6vdv4-mhsqxrczwv0ofb.16000091764745653" },
    { fileId: "1ahb6W9Cjkzty3s4hAoPpAZJr_0MxvyvT", label: "lv_0_20260508095128" },
    { fileId: "10ErcG6PSq6PltMwDW0BX_Zx5MlKnRrF9", label: "lv_0_20260508100859" },
  ],
  "1269": [
    { fileId: "1N61zCX1sSYGuOdTVlTfudtshlPOqCokn", label: "id-11110105-6vdvi-mf0i4d1dpukv92.16000031758677357" },
    { fileId: "1rifW4AZ_L-XrmPlJ4tv8IaYYNujXGZ1A", label: "snaptik_7636299082763472149_v3" },
    { fileId: "19kgrHa_O_4PrI0VsLWMaDbRH_uoIsvD-", label: "snaptik_7641055575131933973_v3" },
  ],
  "1272": [
    { fileId: "1dp6l6wlU9D6VG3fhvygXWxo4XUhgF4gU", label: "id-11110105-6vdv4-mfdouebgyhaief.16000041759475611" },
  ],
  "1274": [
    { fileId: "1NQp0RRAl6gZ1W6x1UJEwnQ0S8zI5iRX3", label: "download (2)" },
  ],
  "1275": [
    { fileId: "1-5mS-aMk4fA2SXBn2M1tgHefcd-4keSA", label: "download" },
    { fileId: "1UO5CfI0syzDS6Jpdd7PD_jpTDjd1F2bv", label: "id-11110105-6vg6r-mlhg657c78qo83.16000041772778604" },
    { fileId: "1QO5YuAdC-HOMAGtBwHCsjmuhVISS5mKg", label: "lv_0_20260521214111" },
  ],
  "1283": [
    { fileId: "1xY_TBO2XvmsEkLRFS1QHa_HGg1Jk05Zs", label: "Akhirnya Mobil Expander Sampai ke Rumah Mas Zainal" },
    { fileId: "10IWXrHXtCmMtuYgpWPl4tQ7U1rM6zmBn", label: "Siapa lagi yang ingin mendapatkan REWARD MOBIL" },
    { fileId: "1McHogNUfxmKnt8u9vdgLV4JxhHAKedsX", label: "#OSBGame" },
  ],
  "1326": [
    { fileId: "1XBygpAJ0X9Wm0W1XCRm1PFDMLHJiYYpL", label: "Bikin toilet kamu makin wangi dan bersih! Bisa basmi kuman juga loh, kalo basmi mulut netizen siiii kayaknya…. Bisa juga. Ayo langsung checkout!" },
    { fileId: "1sBUqjb6Z4lf5-kXVSZsktXBtjCUCFPPH", label: "gammadzaki - 7573406627194359048" },
    { fileId: "1J-cVVlMVzckq7MRbYuP2nWPhWSoO-hoi", label: "Glow home pembersih toilet dan desinfektan" },
  ],
  "1357": [
    { fileId: "1XRtUKQzYrogytP2SfHsXcEIsOegdEd26", label: "Asset 1" },
    { fileId: "1XkCQHj2qJ-Mfsm7aPtdNQ3XwAcUTm4JN", label: "Asset 2" },
    { fileId: "1KuGiUJnUnWXFtRT6rQfeXVlIW7Lhbwp8", label: "7634160517979983125" },
  ],
  "1754": [
    { fileId: "1sN0OsvYTAuwZ_GhBztHNOFV57mCRuhed", label: "mentahanpengemuk1" },
    { fileId: "1EC-E-oDHiuCp9NhroNvixZDnoEiJ5Kf_", label: "mentahanpengemuk10" },
    { fileId: "1RYlE6Mpr5HwanTtnSPX8gV_G9L5QwagH", label: "mentahanpengemuk2" },
  ],
  "2145": [
    { fileId: "13qrPe2r1rmot6Gtz3_D9xuMTaKTK7n_Z", label: "M10formula" },
    { fileId: "1Z8Gs1EdM-DILWftyooq90XKqa1q4OS1E", label: "M11formula" },
    { fileId: "15K5NQ3iUlLUlCK3M9AJZ39aE3TULHQ82", label: "M12formula" },
  ],
  "2149": [
    { fileId: "1j3KlgD0-DH0gjzdQF8y5nrvcvud5CquW", label: "Formula 1" },
    { fileId: "1dZRlBcV39-Ppnlg-y-i-CZ-ihYGsBuUi", label: "Formula 2" },
    { fileId: "1u8elh5GSB6xREvWcW7Hw9LhDja8fXqQH", label: "Formula 3" },
  ],
};

export function getProductVideos(productId: string): ProductVideo[] {
  return VIDEOS[productId] ?? [];
}

export function driveEmbedUrl(fileId: string): string {
  return `https://drive.google.com/file/d/${fileId}/preview`;
}

export function driveStreamUrl(fileId: string): string {
  return `https://drive.usercontent.google.com/download?id=${fileId}&export=download`;
}